import os
from dotenv import load_dotenv
from agents import Agent, function_tool
from agents.extensions.models.litellm_model import LitellmModel

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in .env file")

@function_tool
def SummarizerTool(pdf_text: str) -> str:
    """
    Summarizes the provided PDF text into a clear, structured format
    with headings and bullet points.
    """
    
    return "Summary generated by AI." 


@function_tool
def QuizGeneratorTool(pdf_text: str) -> str:
    """
    Generates a multiple-choice quiz with a minimum of 5 questions,
    each with 4 options (A, B, C, D), from the provided PDF text.
    The correct answer for each question should be clearly marked.
    """
   
    return "Quiz generated by AI."

system_prompt = """
You are an AI study assistant that helps students learn.

When a user uploads a PDF:
1. Extract and summarize the content in clear, structured format using the SummarizerTool.
2. Wait for user to request a quiz.
3. Generate quiz questions from the ORIGINAL PDF text (not the summary) using the QuizGeneratorTool.
4. Create MCQs with 4 options each, clearly mark correct answers (e.g., "A) Option A ✅").
5. Ensure there are at least 5 quiz questions.
6. Stream all responses progressively.
"""

agent = Agent(
    name="PDF Study Assistant",
    instructions=system_prompt,
    model=LitellmModel(
        model="gemini/gemini-2.5-flash",
        api_key=GEMINI_API_KEY
    ),
    tools=[SummarizerTool, QuizGeneratorTool]
)
